apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tg-createupdate
  name: tg-createupdate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-createupdate
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tg-createupdate
    spec:
      containers:
        - image: tg-createupdate
          name: tg-createupdate
          resources: {}
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tg-createupdate
  name: tg-createupdate
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tg-createupdate
  type: ClusterIP
status:
  loadBalancer: {}
