server:
  port: 8080
spring:
  application:
    name: tarabut-create-update
  datasource:
    url: jdbc:postgresql://host.docker.internal/tarabut
    driverClassName: org.postgresql.Driver
    userName: postgres
    password: tarabut123
    platform: org.hibernate.dialect.Postgresql
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

# feign client configuration
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      getCustomerClient:
        connectTimeout: 40000
        readTimeout: 40000
        loggerLevel: ${log.level.feign:full}

getCustomerClient:
  customer:
    url: /customer
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://host.docker.internal:8090

